"""scores_for_tasks

Revision ID: 78763b3bf41c
Revises: 659786a75803
Create Date: 2022-02-22 14:22:38.656795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78763b3bf41c'
down_revision = '659786a75803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scores', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scores')
    # ### end Alembic commands ###
