"""wins

Revision ID: 8221e612baa2
Revises: c14c92d263c4
Create Date: 2022-04-02 15:27:45.295153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8221e612baa2'
down_revision = 'c14c92d263c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wins')
    # ### end Alembic commands ###
